### PR TITLE
Update code for latest nightly builds

### PR DESCRIPTION
**Pull request by NycroV**
A couple of noteworthy changes here:

- Reflection is no longer used to hook events - the handlers are now triggered through a transient service as part of DSharpPlus' new event handler implementations

- Connected shard count retrieval still has default implementations, but if an end-user is using a custom `IShardOrchestrator` implementation, for the most accurate shard count retrieval they should supply their own Task.

Example:
`builder.Services.Configure<DiscordClientWrapper>(wrapper => wrapper.GetShardCount = () => YourTask());`

Additionally, if your shard count retrieval needs to make asynchronous calls:
`builder.Services.Configure<DiscordClientWrapper>(wrapper => wrapper.GetShardCount = async () => await YourTaskAsync());`

Obviously you can skip the lambda expressions and directly insert the method name, but I used lambda here to make it more obvious what's actually being done.

This won't be relevant for 99% (if not 100%) of users, as D#+'s default implementations are usually more than fine enough. However, I'm still going to reach out to D#+ to see about implementing a connected shard count property or method on the `IShardOrchestrator` interface. This would allow us to forego all of this extra roundabout retrieval and directly access the counts without the need for any additional configuration from end users.

### CODE REVIEW

**Comment by akiraveliara** [comment]
> This won't be relevant for 99% (if not 100%) of users, as D#+'s default implementations are usually more than fine enough. However, I'm still going to reach out to D#+ to see about implementing a connected shard count property or method on the IShardOrchestrator interface. 

hej, D#+ maintainer here - this will be available shortly: https://github.com/DSharpPlus/DSharpPlus/pull/2068

**Comment by NycroV** [comment]
Once the DSharpPlus PR has been merged and published, all that needs to be changed is updating the L4N .csproj information to use the latest nightly package, and then this PR will be ready to merge.

Thanks @akiraveliara for the speedy response and implementation!

**Comment by NycroV** [comment]
DSharpPlus package has been updated and this PR is now ready to merge!

**Comment by angelobreuer** [comment]
Thank you 🚀

**Pull request merged**
