### PR TITLE
Add ClusterNodeFactory, allow to override cluster node creation

### LINKED ISSUE #94: Allow extending LavalinkClusterNode
*After recent changes, it became difficult to update my fork library (because a big difference between the codebase has accumulated) and I want to port some of my changes to upstream, which would give up using the fork.*

**Is your feature request related to a problem? Please describe.**
In my bot i need to perform a custom actions when bot is kicked from the channel. Yes, it can be done in the global discordnet handler, but I need to change the behavior of the library when receiving an event from discord.

**Describe the solution you'd like**
- Make LavalinkClusterNode non sealed and allow overriding VoiceStateUpdated. 
- Allow creating user defined node implementations in LavalinkCluster (may be via factory defined at LavalinkClusterOptions) 

**Additional context**
May be good idea is a create generic LavalinkCluster for using with a user node implementations.  
My implementation [here](https://gitlab.com/enlivenbot/Lavalink4NET/-/commit/0b3cabf5831ea71560ba8df4a353af179dc794e8) (its not perfect, but worked for me)

### PR DESCRIPTION
**Pull request by SKProCH**
This PR closes #94 
### Changes
- Make `LavalinkClusterNode` non sealed to allow override certain actions
- Add `ClusterNodeFactory`
- Add `ClusterNodeFactory` property to ClusterOptions

### CODE REVIEW

**Comment by angelobreuer** [comment]
Is there a reason why the generic parameter for the node is not inlined? I think the factory always has the type argument `LavalinkClusterNode`

**Comment by SKProCH** [comment]
@angelobreuer Actually there is no such reason, I just did as it is implemented in `PlayerFactory`. Should i fix that?

**Comment by angelobreuer** [comment]
I think the reason for that was that the JoinAsync method uses the factory to ensure the player has a static generic type as the player itself is returned to the user. The cluster node is only consumed by the library code.

image

You can see that the result of the factory is not statically typed as it is just typed to LavalinkClusterNode:

image

**Comment by angelobreuer** [comment]
Perfect! Thanks!

**Comment by SKProCH** [comment]
@angelobreuer 
How can I use the version with dev changes in my project? 
Also, thanks for the great library and quick support! This is awesome!

**Comment by angelobreuer** [comment]
I will trigger the CI to push a new preview of Lavalink4NET 3, so your changes are then live in the preview versions (3.0.0-preview.4)

**Pull request merged**
