### PR TITLE
Add Lyrics.Java support

### PR DESCRIPTION
**Pull request by KMen1**
I have found great use of the [Lyrics.Java](https://github.com/DuncteBot/java-timed-lyrics) plugin and think it would be great to have native support for it in Lavalink4NET!

This integration 
- Automatically fetches the lyrics for the current track in `NotifyLyricsLoadedAsync`.
- Adds `GetCurrentTrackLyricsAsync`, `GetYoutubeLyricsAsync`, `GetGeniusLyricsAsync` and `SearchAsync` extension methods to `ILavalinkApiClient`. 
- Adds documentation for the integration and updates the readme to include it

If looking forward to getting feedback on this PR and hopefully getting it merged!

### CODE REVIEW

**Comment by angelobreuer** [comment]
Very cool 🎉 thank you a lot!

**Comment by angelobreuer** [comment]
Linking https://github.com/DuncteBot/java-timed-lyrics/issues/4

**Comment by angelobreuer** [comment]
Can you take a look at the modifications I made and check if they suit your use-case? Maybe there is something you find odd or could be improved

**Comment by KMen1** [comment]
Yes, it's perfect like this 👌

**Pull request merged**
